#!/usr/bin/bash

set -e

function help() {
  cat >&2 << EOF

  This script supports local container registry management

  Usage: ${SCRIPTNAME} <command> <options>

  Commands:

  * setup --username <USERNAME> --password <PASSWORD> --directory <DIRECTORY_PATH> : setup local container registry 

  * start  : start local container registry 
  
  * status : check status of local container registry

  * stop   : stop local container registry

  * delete  : delete local container registry, remove both data and configuration

EOF
}

function parse_args() {

  # Check COMMAND existence
  if [ -z $1 ]
  then
    echo 'ERROR: Missing command.'
    help
    exit 1
  fi

  case $1 in
    setup)
      shift 1
      setup $@
      ;;
    start)
      shift 1
      start
      ;;
    status)
      shift 1
      status
      ;;
    stop)
      shift 1
      stop
      ;;
    delete)
      shift 1
      delete 
      ;;
    help|--help|-h)
      help
      exit 0
      ;;
    *)
      echo "Error. Unrecognized command: $1" >&2
      help
      exit 1
      ;;
  esac
}

function setup_parse_args() {
  while [ -n $1 ] && [ "$1" != "" ]
  do
    case $1 in
      "--username"|"-u")
        shift 1
        USERNAME="$1"
        shift 1
        ;;
      "--password"|"-p")
        shift 1
        PASSWORD="$1"
        shift 1
        ;;
      "--directory"|"-d")
        shift 1
        DIRECTORY=$(readlink -f "$1")
        shift 1
        ;;
      help|--help|-h)
        help
        exit 0
        ;;
      *)
        echo "Error. Unrecognized command: $1" >&2
        help
        exit 1
        ;;
    esac
  done
}

function setup() {
  setup_parse_args $@

  [ -z ${USERNAME} ] && echo "ERROR: missing USERNAME specification" >&2 && exit 1
  [ -z ${PASSWORD} ] && echo "ERROR: missing PASSWORD specification" >&2 && exit 1
  [ -z ${DIRECTORY} ] && echo "ERROR: missing DIRECTORY specification" >&2 && exit 1
  [ ! -d ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY ${DIRECTORY}" >&2 && exit 1

  LOCAL_ADDRESS=$(hostname)
  [ -z ${LOCAL_ADDRESS} ] && echo "ERROR: cannot find LOCAL_ADDRESS for local container registry" >&2 && exit 1

  # Lock
  lock

  # Create authentication file
  cd ${DIRECTORY}
  mkdir -p ./auth
  podman run --rm --entrypoint htpasswd docker.io/httpd:2 -Bbn "${USERNAME}" "${PASSWORD}" > auth/htpasswd 2>/dev/null

  # Create new certificates
  mkdir -p ./certs
  openssl req -newkey rsa:4096 \
  -nodes -sha256 \
  -keyout certs/domain.key \
  -addext "subjectAltName = DNS:${LOCAL_ADDRESS}" \
  -x509 \
  -days 365 \
  -out certs/domain.crt \
  -subj "/C=CH/ST=TI/L=Lugano/O=Private/OU=None/CN=${LOCAL_ADDRESS}" 2>/dev/null
  
  # Create data directory
  mkdir -p ./data

  # Save Local Address
  mkdir -p ./etc
  echo "${LOCAL_ADDRESS}" > etc/local_address.conf

  # Save Registry Directory
  LOCAL_ADDRESS_FILE="${USER_CONF_DIR}/${LOCAL_ADDRESS}.conf"
  [ ! -e "${USER_CONF_DIR}" ] && mkdir -p ${USER_CONF_DIR}
  [ ! -d "${USER_CONF_DIR}" ] && echo "ERROR: ${USER_CONF_DIR} is not a directory" >&2 && exit 1
  if [ -f "${LOCAL_ADDRESS_FILE}" ] 
  then
    OLD_DIRECTORY=$(cat "${LOCAL_ADDRESS_FILE}")
    if [ "${DIRECTORY}" != "${OLD_DIRECTORY}" ]
    then
      echo "Overriding previous local container registry directory setting for ${LOCAL_ADDRESS}" >&2
      echo "Previous local container registry for ${LOCAL_ADDRESS} was at ${OLD_DIRECTORY}" >&2
      echo "" >&2
    fi
  fi
  echo "${DIRECTORY}" > ${LOCAL_ADDRESS_FILE}
  
  # unlock
  unlock

  echo "Local container registry for ${LOCAL_ADDRESS} at ${DIRECTORY} is setup." >&2
}

function start() {
  LOCAL_ADDRESS=$(hostname)
  [ -z ${LOCAL_ADDRESS} ] && echo "ERROR: cannot find LOCAL_ADDRESS for local container registry" >&2 && exit 1

  LOCAL_ADDRESS_FILE="${USER_CONF_DIR}/${LOCAL_ADDRESS}.conf"
  [ ! -f ${LOCAL_ADDRESS_FILE} ] && echo "ERROR: Missing LOCAL_ADDRESS_FILE at ${LOCAL_ADDRESS_FILE}" >&2 && exit 1

  DIRECTORY=$(cat ${LOCAL_ADDRESS_FILE})
  [ -z ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY for local container registry" >&2 && exit 1
  [ ! -d ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY \"${DIRECTORY}\" for local container registry" >&2 && exit 1

  LOCAL_PORT_FILE="${USER_CONF_DIR}/${LOCAL_ADDRESS}_port.conf"
  DEFAULT_PORT=$(get_default_port)
  LOCAL_PORT=$(find_available_port "${DEFAULT_PORT}")
  [ -z ${LOCAL_PORT} ] && echo "ERROR: cannot find LOCAL_PORT for local container registry" >&2 && exit 1

  set +e
  do_status
  RC=$?
  set -e

  if [ $RC -eq 0 ]
  then
    echo "ERROR: local container registry is ALREADY running." >&2
    exit 1
  fi

  # Lock
  lock

  # Run
  podman run -d \
  -p ${LOCAL_PORT}:5000 \
  --restart=always \
  --name ${CONTAINER_NAME} \
  -v "${DIRECTORY}/auth":/auth \
  -v "${DIRECTORY}/certs":/certs \
  -v "${DIRECTORY}/data":/var/lib/registry \
  -e REGISTRY_AUTH="htpasswd" \
  -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH="/auth/htpasswd" \
  -e REGISTRY_HTTP_TLS_CERTIFICATE="/certs/domain.crt" \
  -e REGISTRY_HTTP_TLS_KEY="/certs/domain.key" \
  docker.io/registry:3 &>/dev/null

  # Save Local Port
  echo "${LOCAL_PORT}" > "${LOCAL_PORT_FILE}"

  echo "Local container registry ( use option --tls-verify=false ) started on folder ${DIRECTORY}" >&2
  echo "The address is:" >&2
  echo "${LOCAL_ADDRESS}:${LOCAL_PORT}" >&1
  echo "" >&2
  echo "Run this command before using it:" >&2
  echo "podman login --tls-verify=false ${LOCAL_ADDRESS}:${LOCAL_PORT}" >&2
}

function do_status() {
  STATUS=$(podman container inspect "${CONTAINER_NAME}" 2>/dev/null | jq -r '.[].State.Status')
  if [ "${STATUS}" == "running" ]
  then
    return 0
  else
    return 1
  fi
}

function stop() {
  LOCAL_ADDRESS=$(hostname)
  [ -z ${LOCAL_ADDRESS} ] && echo "ERROR: cannot find LOCAL_ADDRESS for local container registry" >&2 && exit 1

  LOCAL_ADDRESS_FILE="${USER_CONF_DIR}/${LOCAL_ADDRESS}.conf"
  DIRECTORY=$(cat ${LOCAL_ADDRESS_FILE})
  [ -z ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY for local container registry" >&2 && exit 1
  [ ! -d ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY \"${DIRECTORY}\" for local container registry" >&2 && exit 1

  set +e
  podman container stop "${CONTAINER_NAME}" &>/dev/null
  podman container rm "${CONTAINER_NAME}" &>/dev/null

  do_status
  RC=$?
  set -e

  if [ $RC -eq 0 ]
  then
    echo "ERROR: local container registry is STILL running." >&2
  else
    unlock
    echo "local container registry is stopped." >&2
  fi
}

function delete() {
  LOCAL_ADDRESS=$(hostname)
  [ -z ${LOCAL_ADDRESS} ] && echo "ERROR: cannot find LOCAL_ADDRESS for local container registry" >&2 && exit 1
  
  LOCAL_ADDRESS_FILE="${USER_CONF_DIR}/${LOCAL_ADDRESS}.conf"
  [ ! -f ${LOCAL_ADDRESS_FILE} ] && echo "ERROR: Missing LOCAL_ADDRESS_FILE at ${LOCAL_ADDRESS_FILE}" >&2 && exit 1

  LOCAL_PORT_FILE="${USER_CONF_DIR}/${LOCAL_ADDRESS}_port.conf"
  DIRECTORY=$(cat ${LOCAL_ADDRESS_FILE} 2>/dev/null) || true
  [ -z ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY for local container registry" >&2 && exit 1
  [ ! -d ${DIRECTORY} ] && echo "ERROR: cannot find DIRECTORY \"${DIRECTORY}\" for local container registry" >&2 && exit 1

  set +e
  do_status
  RC=$?
  set -e

  if [ $RC -eq 0 ]
  then
    echo "ERROR: local container registry is STILL running." >&2
    exit 1
  fi

  # Lock
  lock

  # Clean data
  echo -n "Removing directory ${DIRECTORY} content ... " >&2
  rm -rf ${DIRECTORY}/.lock && \
  rm -rf ${DIRECTORY}/auth && \
  rm -rf ${DIRECTORY}/certs && \
  rm -rf ${DIRECTORY}/data && \
  rm -rf ${DIRECTORY}/etc && \
  echo "[DONE]" >&2
  echo -n "Removing configuration file ${LOCAL_PORT_FILE} ... " >&2
  rm -rf ${LOCAL_PORT_FILE} && echo "[DONE]" >&2
  echo -n "Removing configuration file ${LOCAL_ADDRESS_FILE} ... " >&2
  rm -rf ${LOCAL_ADDRESS_FILE} && echo "[DONE]" >&2
  echo "" >&2
  echo "local container registry is DELETED." >&2

}

function lock() {
  local LOCK_FILE="${DIRECTORY}/.lock"
  if [ -f "${LOCK_FILE}" ]
  then
    LOCKING_ADDRESS=$(cat ${LOCK_FILE})
    if [ "${LOCKING_ADDRESS}" == "${LOCAL_ADDRESS}" ]
    then
      
      # Wait for concurrency prevention
      LOCK_AGE=$(stat -c %Y ${LOCK_FILE})
      NOW=$(date +%s)
      [ $((NOW - LOCK_AGE)) -lt 3 ] && sleep 3

      set +e
      do_status
      RC=$?
      set -e
      
      if [ $RC -eq 0 ]
      then
        echo "ERROR: local container registry is running."
        return 1
      else
        touch ${LOCK_FILE}
        return 0
      fi
     else
       echo "ERROR: local container registry is locked by ${LOCKING_ADDRESS}"
       return 1
    fi
  else
    echo "${LOCAL_ADDRESS}" > ${LOCK_FILE}
  fi
}

function unlock() {
  local LOCK_FILE="${DIRECTORY}/.lock"
  if [ -f "${LOCK_FILE}" ]
  then
    LOCKING_ADDRESS=$(cat ${LOCK_FILE})
    if [ "${LOCKING_ADDRESS}" == "${LOCAL_ADDRESS}" ]
    then
      rm -f ${LOCK_FILE}
    else
      echo "ERROR: local container registry is locked by ${LOCKING_ADDRESS}"
      return 1
    fi
  fi
}

function get_default_port() {
  local ORIG_PORT=5000
  local DESIGNED_PORT=""
  [ -f ${LOCAL_PORT_FILE} ] && DESIGNED_PORT=$(cat ${LOCAL_PORT_FILE})
  [ -z "${DESIGNED_PORT}" ] && DESIGNED_PORT=${ORIG_PORT}
  echo ${DESIGNED_PORT}
}

function find_running_port() {
  podman container inspect ${CONTAINER_NAME} | jq -r '.[].NetworkSettings.Ports."5000/tcp"[0].HostPort'
}

function find_available_port() {

  local DESIGNED_PORT="$1"
  if [ -n "${DESIGNED_PORT}" ] && [ ${DESIGNED_PORT} -gt 0 ]
  then
    PORT_STATE=$(ss -Htan | awk '{print $4}' | cut -d':' -f2 | grep -w "${DESIGNED_PORT}" && echo BUSY || echo FREE)
    if [ "${PORT_STATE}" == "FREE" ]
    then
      echo ${DESIGNED_PORT}
      return 0
    fi
  fi

  MIN_PORT_RANGE=$(cat /proc/sys/net/ipv4/ip_local_port_range | cut -f1)
  MAX_PORT_RANGE=$(cat /proc/sys/net/ipv4/ip_local_port_range | cut -f2)
  comm -23 \
  <(seq "$MIN_PORT_RANGE" "$MAX_PORT_RANGE" | sort) \
  <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) \
  | shuf | head -n "1"
}

function status() {
  LOCAL_ADDRESS=$(hostname)

  set +e
  do_status
  RC=$?
  set -e

  if [ $RC -eq 0 ]
  then
    LOCAL_PORT=$(find_running_port)
    echo "local container registry ( use option --tls-verify=false ) is running at:" >&2
    echo "${LOCAL_ADDRESS}:${LOCAL_PORT}" >&1
  else
    echo "local container registry is stopped." >&2
  fi
}

CONTAINER_NAME="local_container_registry"
USER_CONF_DIR="${HOME}/.local_container_registry"

parse_args $@

exit 0


